# ===========================================
# CONFIGURAÇÃO DECAP CMS - CAROMÊ
# ===========================================

backend:
  name: github
  repo: felipepereira160-a11y/SiteMacrame
  branch: main
  auth_token: "{{GITHUB_TOKEN}}"

media_folder: assets/images/uploads
public_folder: /assets/images/uploads

collections:

  # 1️⃣ PRODUTOS
  - name: produtos
    label: Produtos da Loja
    label_singular: Produto
    description: Adicione, edite ou remova produtos da loja.
    
    files:
      - name: lista_de_produtos
        label: Lista de Produtos
        file: content/products.json
        format: json
        fields:
          - label: ID (slug)
            name: id
            widget: string
            hint: Identificador único, ex: painel-conchas
          - label: Título
            name: title
            widget: string
          - label: Preço
            name: price
            widget: string
            hint: Ex: R$ 69,90
          - label: Imagem Principal
            name: image
            widget: image
            hint: Imagem que aparece no card principal.
          - label: Galeria (Opcional)
            name: images
            widget: list
            field:
              label: Imagem
              name: img
              widget: image
            hint: Imagens adicionais do produto.
          - label: Descrição
            name: description
            widget: text
          - label: Características
            name: features
            widget: list
            field:
              label: Item
              name: item
              widget: string
            hint: Cada item vira um tópico na lista.
          - label: Link do WhatsApp
            name: whatsapp
            widget: string
            hint: Link completo (https://wa.me/...)

  # 2️⃣ TEXTOS DO SITE (Sobre e FAQ)
  - name: paginas
    label: Conteúdo do Site
    files:
      - name: textos
        label: Textos (Sobre e FAQ)
        file: content/siteData.json
        format: json
        fields:
          - label: Seção 'Quem Somos'
            name: sobre
            widget: object
            fields:
              - label: Texto Introdutório
                name: intro
                widget: text

          - label: Perguntas Frequentes (FAQ)
            name: faq
            widget: list
            fields:
              - label: Pergunta
                name: pergunta
                widget: string
              - label: Resposta
                name: resposta
                widget: text
